spring:
  datasource:
    url: jdbc:postgresql://database:5432/consultants
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true






#spring.datasource.url= ${url}
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
##spring.datasource.password=password
#pring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true
#spring.h2.console.settings.web-allow-others=true


# Specify the path of the OpenAPI documentation
#springdoc.api-docs.path=/api-docs
# Specify the path of the Swagger UI
#springdoc.swagger-ui.path=/swagger-ui.html
# Enable or disable Swagger UI
#springdoc.swagger-ui.enabled=true